services:
  newbalance:
    container_name: newbalance
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - /home/opc/Docker/NewBalance-release:/app
    restart: unless-stopped
    expose:
      - 3000  # Expose uniquement en interne pour Traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.newbalance.rule=Host(`release.luku.fr`)"
      - "traefik.http.routers.newbalance.entrypoints=websecure"
      - "traefik.http.routers.newbalance.tls.certresolver=lets-encrypt"
      - "traefik.http.services.newbalance.loadbalancer.server.port=3000"
    networks:
      - web

networks:
  web:
    external: true

